services:
  laravel-docker:
    container_name: Rentella_app
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    entrypoint: ["/bin/sh", "/var/www/html/deployment/entrypoint.sh"]
    volumes:
      - ../:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - mysql_db
    networks:
      - keycloak-network
  vue:
    container_name: vue
    build:
      context: ../../web/
      dockerfile: Dockerfile
    ports:
      - "5173:8000"
    volumes:
      - ../../web/:/var/www/html/app
      - /var/www/html/app/node_modules
    networks:
      - keycloak-network
  cors:
    build:
      context: ./
      dockerfile: cors.Dockerfile
    container_name: cors
    ports:
      - "4545:80"
    networks:
      - keycloak-network
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-Rentella_db}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-change_me_mysql_root}
    ports:
      - 3306:3306
    networks:
      - keycloak-network
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-keycloak}
      POSTGRES_USER: ${POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me_postgres}
    networks:
      - keycloak-network
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    ports:
      - 8080:8080
    command: ${KEYCLOAK_START_COMMAND:-start --optimized --import-realm}
    volumes:
      - ../themes/Rentella:/opt/keycloak/themes/Rentella
      - ./keycloak/realm-rentella.json:/opt/keycloak/data/import/realm-rentella.json
      - keycloak_standalone_data:/opt/jboss/keycloak/standalone/data
      - keycloak_standalone_deployments:/opt/jboss/keycloak/standalone/deployments
    environment:
      KEYCLOAK_LOGLEVEL: ${KEYCLOAK_LOGLEVEL:-INFO}
      KC_HOSTNAME_STRICT_HTTPS: ${KC_HOSTNAME_STRICT_HTTPS:-true}
      KC_HTTP_ENABLED: ${KC_HTTP_ENABLED:-false}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-keycloak}
      DB_DATABASE: ${POSTGRES_DB:-keycloak}
      KC_DB_USERNAME: ${POSTGRES_USER:-keycloak}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-change_me_postgres}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-change_me_keycloak_admin}
    depends_on:
      - postgres
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
volumes:
  postgres_data:
  keycloak_standalone_data:
  keycloak_standalone_deployments:
